services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LIMITER_IP_MAX_REQUESTS=5
      - LIMITER_IP_BLOCK_DURATION=5m
      - LIMITER_TOKEN_MAX_REQUESTS=10
      - LIMITER_TOKEN_BLOCK_DURATION=5m
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
